Updating README and making modifications for macos to run (need to allow network calls)
brongan/brongnal pull request #21
Opened 2024-08-28 15:38 UTC by dayandersen

2024-08-29 03:34 UTC, brongan requested changes

2024-08-29 03:34 UTC, brongan commented on pubspec.lock
Please revert changes to this file.

2024-08-29 03:34 UTC, brongan commented on README.md
> +cargo r -p client $USER http://localhost:8080
I mean I guess gRPC is over http/2

2024-09-04 14:50 UTC, dayandersen commented on pubspec.lock
Second commit reverts.

2024-09-04 16:33 UTC, brongan approved these changes

2024-09-06 16:13 UTC, merged